server:
  port: 4040

spring:
  application:
        name: Cafe Order Backend Application
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      timeout: 30m
  cache:
    type: simple

logging:
  level:
      root: INFO
  file: logs/cafe_order_backend.log